# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      TAUDEM_PATH: TauDEM/bin
    steps:
      - uses: actions/checkout@v2

      - name: Install required pkgs for linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install gdal-bin libgdal-dev mpich

      - name: Install required pkgs for mac
        if: runner.os == 'macOS'
        run: |
          brew install gdal mpich

      - name: Install TauDEM on linux and mac
        if: runner.os != 'Windows'
        run: sh ./TauDEM.sh

      - name: Install TauDEM on Windows
        if: runner.os == 'Windows'
        run: |
          cd $HOME
          curl -sLO https://github.com/dtarb/TauDEM/releases/download/v5.3.7/TauDEM537_setup.exe
          .\TauDEM537_setup.exe /SILENT


      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE, run_dont_run = TRUE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          clean: false
          branch: gh-pages
          folder: docs
