on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Check Package

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  TauDEM:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      TAUDEM_PATH: TauDEM/bin

    steps:
      - uses: actions/checkout@v3

      - name: Install required pkgs for linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install gdal-bin libgdal-dev mpich

      - name: Install required pkgs for mac
        if: runner.os == 'macOS'
        run: |
          brew install gdal mpich

      - name: Install TauDEM on linux and mac
        if: runner.os != 'Windows'
        run: sh ./TauDEM.sh

      - name: Install TauDEM on Windows
        if: runner.os == 'Windows'
        run: |
          curl -sLO https://github.com/dtarb/TauDEM/releases/download/v5.3.7/TauDEM537_setup.exe
          .\TauDEM537_setup.exe /SILENT

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
